version: '3.8'

services:
  datagen:
    build: datagen
    container_name: mongodb-cloud-datagen
    restart: unless-stopped
    environment:
      MONGO_URI: ${MONGO_URI}
      MONGO_DB_NAME: ${MONGO_DB_NAME:-estuary_raw}
      OPENAI_API_KEY: ${OPENAI_API_KEY}

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - metabase-data:/metabase-data
    environment:
      MB_DB_FILE: /metabase-data/metabase.db

volumes:
  metabase-data:
